import type { Vehicle } from './types'

export const CATALOG: Record<string, string[]> = {
  JETOUR: [
    'X50 1.5 4X2 5MT CONFORT',
    'X50 1.5 4X2 6DCT LIMITED',
    'X70 FL 1.5T 6MT 4X2 FULL',
    'X70 FL 1.5T 6MT 4X2 DELUX',
    'X70 FL 1.5T 6DCT 4X2 LIMITED',
    'DASHING 1.5T 6MT CONFORT ACP',
    'DASHING 1.5T 6DCT CONFORT ACP',
    'DASHING 1.6T 7DCT ACP',
    'T1 1.5T 4X2 7DCT',
    'T1 2.0T AWD 8AT',
    'T1 1.5T 4X2 PHEV',
    'TRAVELLER T2 2.0T AWD 7DCT LIMITED',
    'TRAVELLER T2 1.5T 4X2 PHEV',
  ],
  SOUEAST: [
    'S06 1.5T 6DCT',
    'S06 1.5T 7DCT',
    'S07 1.5T 6MT',
    'S07 1.5T 6DCT',
    'S07 1.6T 7DCT',
    'S09 1.6T 7DCT',
    'S09 AWD 2.0T',
  ],
  KYC: [
    'MINITRUCK NEW T3 C/S',
    'MINITRUCK NEW T3 D/C',
    'MINITRUCK NEW T3 FURGON',
    'MINITRUCK T3 REFRIGERADO',
    'MINITRUCK NEW X5',
    'MINITRUCK NEW X5 REFRIGERADO',
    'NEW V3 PANEL',
    'NEW V3 1.5 MEC PANEL',
    'NEW V3 CONFORT (SIN A/C)',
    'NEW V3 FULL (CON A/C)',
    'NEW V3 PLUS (CON A/C)',
    'NEW V5 CONFORT (SIN A/C)',
    'NEW V5 PLUS (CON A/C)',
    'NEW V7 PLUS (CON A/C)',
  ],
  YOUTONG: [],
}

export const MARCAS = Object.keys(CATALOG)

export const UBICACIONES = [
  'LAVADERO',
  'GRUPO HS',
  'DON PANCHO',
  'TIENDA PRINCIPAL',
  'TIENDA POSTERIOR',
  'NUEVO LOCAL',
]

export const ASESORES = ['VLADIMIR', 'ALVARO', 'WAGNER', 'DIEGO', 'ADMINISTRACION']

export const ESTADOS = ['LIBRE', 'SEPARADO', 'VENDIDO', 'FINANCIADO'] as const

export const SITUACIONES = ['PENDIENTE', 'ENTREGADO'] as const

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: '1',
    fechaFactura: '2026-06-16',
    vin: 'LSCABN3E6TE144524',
    marca: 'KYC',
    modelo: 'MINITRUCK NEW T3 C/S',
    color: 'BLANCO',
    cliente: '',
    precioCompra: 10499.7,
    precioVenta: 10790,
    fechaLlegada: '2026-06-26',
    ubicacion: 'LAVADERO',
    codigo: '5656',
    asesor: 'VLADIMIR',
    estado: 'LIBRE',
    situacion: 'PENDIENTE',
    observaciones: 'FSFDFDS',
  },
  {
    id: '2',
    fechaFactura: '2026-08-10',
    vin: 'LVTDB11B1VDC16992',
    marca: 'JETOUR',
    modelo: 'X70 FL 1.5T 6MT 4X2 FULL',
    color: 'ROJO',
    cliente: 'MARIO DELGADO VALDIVIA',
    precioCompra: 18850.8,
    precioVenta: 21190,
    fechaLlegada: '2026-08-20',
    ubicacion: 'GRUPO HS',
    codigo: '6556',
    asesor: 'ALVARO',
    estado: 'VENDIDO',
    situacion: 'ENTREGADO',
    observaciones: 'FDS',
  },
  {
    id: '3',
    fechaFactura: '2026-03-19',
    vin: 'LVTDB11B2VH506096',
    marca: 'JETOUR',
    modelo: 'X70 FL 1.5T 6MT 4X2 FULL',
    color: 'NEGRO',
    cliente: 'CELSO PRIETO',
    precioCompra: 18850.8,
    precioVenta: 21190,
    fechaLlegada: '2026-03-29',
    ubicacion: 'GRUPO HS',
    codigo: '65',
    asesor: 'VLADIMIR',
    estado: 'VENDIDO',
    situacion: 'ENTREGADO',
    observaciones: '',
  },
  {
    id: '4',
    fechaFactura: '2026-06-20',
    vin: 'LVTDB21B2VH508047',
    marca: 'JETOUR',
    modelo: 'X70 FL 1.5T 6MT 4X2 DELUX',
    color: 'GRIS NARDO',
    cliente: 'ERNTO RAMOS USCA',
    precioCompra: 18850.8,
    precioVenta: 21190,
    fechaLlegada: '2026-06-30',
    ubicacion: 'TIENDA PRINCIPAL',
    codigo: '6565',
    asesor: 'ALVARO',
    estado: 'FINANCIADO',
    situacion: 'PENDIENTE',
    observaciones: 'FDS',
  },
  {
    id: '5',
    fechaFactura: '2026-08-20',
    vin: 'LVTDB21B3VH507036',
    marca: 'JETOUR',
    modelo: 'X50 1.5 4X2 6DCT LIMITED',
    color: 'BLANCO',
    cliente: 'Wilmer aragon',
    precioCompra: 17010.8,
    precioVenta: 19190,
    fechaLlegada: '2026-08-30',
    ubicacion: 'LAVADERO',
    codigo: '151',
    asesor: 'WAGNER',
    estado: 'SEPARADO',
    situacion: 'PENDIENTE',
    observaciones: 'FDS',
  },
  {
    id: '6',
    fechaFactura: '2026-03-19',
    vin: 'LVTDB11B3VH504826',
    marca: 'SOUEAST',
    modelo: 'S06 1.5T 6DCT',
    color: 'NEGRO',
    cliente: '',
    precioCompra: 30930.8,
    precioVenta: 34690,
    fechaLlegada: '2026-03-29',
    ubicacion: 'LAVADERO',
    codigo: '155154',
    asesor: 'DIEGO',
    estado: 'LIBRE',
    situacion: 'PENDIENTE',
    observaciones: 'FDSF',
  },
  {
    id: '7',
    fechaFactura: '2026-06-20',
    vin: 'LVTDB11B2VH507832',
    marca: 'SOUEAST',
    modelo: 'S06 1.5T 7DCT',
    color: 'BLANCO',
    cliente: 'RAUL MARCAVILLA MIFONODO',
    precioCompra: 22530.8,
    precioVenta: 25190,
    fechaLlegada: '2026-06-30',
    ubicacion: 'TIENDA PRINCIPAL',
    codigo: '154541',
    asesor: 'DIEGO',
    estado: 'VENDIDO',
    situacion: 'PENDIENTE',
    observaciones: 'DS',
  },
  {
    id: '8',
    fechaFactura: '2026-08-20',
    vin: 'LVTDB11B2VH507829',
    marca: 'KYC',
    modelo: 'MINITRUCK NEW T3 C/S',
    color: 'NEGRO MATE',
    cliente: 'JESUS FLOREZ QUISPE',
    precioCompra: 34950.8,
    precioVenta: 39690,
    fechaLlegada: '2026-08-30',
    ubicacion: 'TIENDA POSTERIOR',
    codigo: '15154',
    asesor: 'ALVARO',
    estado: 'VENDIDO',
    situacion: 'ENTREGADO',
    observaciones: 'FDSFGRTG',
  },
  {
    id: '9',
    fechaFactura: '2026-03-19',
    vin: 'LVTDD24B6VDC01626',
    marca: 'JETOUR',
    modelo: 'DASHING 1.5T 6MT CONFORT ACP',
    color: 'PLATA',
    cliente: 'LIZANDRO VILLACA ALARCON',
    precioCompra: 34950.8,
    precioVenta: 39690,
    fechaLlegada: '2026-03-29',
    ubicacion: 'GRUPO HS',
    codigo: '15141',
    asesor: 'VLADIMIR',
    estado: 'VENDIDO',
    situacion: 'ENTREGADO',
    observaciones: 'FRGT',
  },
  {
    id: '10',
    fechaFactura: null,
    vin: 'LVTDB11B3VH507287',
    marca: 'JETOUR',
    modelo: 'DASHING 1.6T 7DCT ACP',
    color: 'PLATA',
    cliente: 'CESAR JAIR FERNANDEZ ZAMORA',
    precioCompra: 18850.8,
    precioVenta: 21190,
    fechaLlegada: null,
    ubicacion: 'GRUPO HS',
    codigo: '15414',
    asesor: 'WAGNER',
    estado: 'SEPARADO',
    situacion: 'PENDIENTE',
    observaciones: 'FRERE',
  },
  {
    id: '11',
    fechaFactura: null,
    vin: '',
    marca: '',
    modelo: '',
    color: '',
    cliente: 'JOSE BENJAMIN PALOMINO HUAMAN',
    precioCompra: 25290.8,
    precioVenta: 28190,
    fechaLlegada: null,
    ubicacion: 'LAVADERO',
    codigo: '',
    asesor: 'WAGNER',
    estado: 'SEPARADO',
    situacion: 'PENDIENTE',
    observaciones: '',
  },
]
